# Generated by Django 4.0.1 on 2022-12-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('startprice', models.CharField(max_length=255)),
                ('starttime', models.CharField(max_length=255)),
                ('endtime', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('userid', models.CharField(default='na', max_length=255)),
                ('highprice', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
