# Generated by Django 4.0.1 on 2022-12-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='highprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='startprice',
            field=models.IntegerField(),
        ),
    ]
